# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.CharField(blank=True, default=b'', max_length=255)),
                ('to_emails', models.TextField(blank=True, default=b'')),
                ('cc_emails', models.TextField(blank=True, default=b'')),
                ('bcc_emails', models.TextField(blank=True, default=b'')),
                ('all_recipients', models.TextField(blank=True, default=b'')),
                ('headers', models.TextField(blank=True, default=b'')),
                ('subject', models.TextField(blank=True, default=b'')),
                ('body', models.TextField(blank=True, default=b'')),
                ('raw', models.TextField(blank=True, default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('database_email_backend.email',),
        ),
    ]
